### ISSUE TITLE
custom command input

### ISSUE THREAD

**Issue by stw222** [RayNieport/mconBot#3]
could you add some sort of command like `>cmd (some command other than the default list)`?
I run a spigot server and since that also means i use plugins, i would like to use commands from those without having to add all of the commands to commands.json
of course this feature would be restricted to admins since it enables use of any command

**Comment by RayNieport** [comment]
Hello! I'm finishing up exams for school but I should be able to add this pretty easily in the next week or two!

Would `>admin` work? I can't guarantee that this will work for any arbitrary command, but it should work for most. I run Spigot too, so this might be helpful as an "override" of sorts.

**Comment by stw222** [comment]
ya, that should work

**Comment by RayNieport** [comment]
Hi, this should work now. Try typing `>admin` followed by the command of your choice and it should work. Let me know if you have any issues!

**Comment by RayNieport** [comment]
@stw222 Has this command worked for you as expected? If so I will close the issue.

**Comment by stw222** [comment]
the `>admin` command does seem to work.
