### ISSUE TITLE
React to Messages from Bots

### ISSUE THREAD

**Issue by Fynenix** [RayNieport/mconBot#5]
Is there a way i can modify the script so mconBot also reacts to messages written by other Bots?

I have tried deleting the blue marked code, but that didn't seem to help.
![image](https://user-images.githubusercontent.com/67441473/147355804-ac959117-c1dd-4478-a151-398ac6bfe9c0.png)

**Comment by RayNieport** [comment]
Hi there! As far as I know mconBot should receive commands from other bots just the same as from a user. The other bot would need to be part of the correct role, and would need to begin its message with '>'.

The part of the code that you modified ensures that mconBot cannot read its own message. You can think of "bot.user" in this case to mean "self". This is to prevent any kind of infinite feedback loop. It shouldn't impact other usage with other bots.

I will test interaction with other bots sometime in the next week or two.

**Comment by Fynenix** [comment]
Thanks for your answer. 

Unfortunately it doesnt react to messages from bots.
![SmartSelect_20211224-193513_Discord](https://user-images.githubusercontent.com/67441473/147368995-281caa5f-77eb-4cc4-ae2b-70c498c511ad.jpg)

**Comment by RayNieport** [comment]
Interesting, thanks for bringing this to my attention. I will check it out if I have some time around the holidays. Could you give me a little more information about the bot you are using? Which mconBot role is it a part of in Discord (user, mod, or admin)?

**Comment by Fynenix** [comment]
Okay thanks. 

The bot is from this site. 
https://www.integromat.com/

With a webhook from my Website it sends a message to a specified channel.
![image](https://user-images.githubusercontent.com/67441473/147372668-44a3b24a-889c-4d1c-8a7d-f3bf7cb971c1.png)

The Bot is part of the mod and admin role.

**Comment by RayNieport** [comment]
Hi there, it seems that this is a known issue with discord.py, which is the library that I'm using to interact with Discord. I will look into a work-around.

**Comment by RayNieport** [comment]
@Fynenix I think I got it working. I tested it with another bot and was able to send commands successfully. Can you check and make sure that it's working on your end?

If you need me to update the Docker image, I can do that as well. Right now the fix is only implemented in the source code here on GitHub.

**Comment by Fynenix** [comment]
That's great! Yes, that would be great if you could update the Docker image.

**Comment by RayNieport** [comment]
The docker image raynieport/mconbot:amd64 is up to date now. I'm building the image on my raspberry pi right now, so I'll update the arm64 version as soon as it finishes.

**Comment by RayNieport** [comment]
Hi there, the Docker image is fully up to date for both arm64 and amd64 architectures. Let me know if it works for you!

**Comment by Fynenix** [comment]
Thanks for your efforts. Unfortunately it didn't work. 

I used the following commands to get the new docker image:

docker stop mconbot
sudo docker rm mconbot
sudo docker rmi -f 01ad97a9902e
docker run -dt --name mconbot --env-file .env raynieport/mconbot

Maybe i did something wrong?

I also testet it with the Zapier Bot:
![image](https://user-images.githubusercontent.com/67441473/147460864-217a3193-eed3-4934-95d8-6e5df44c73d1.png)

**Comment by RayNieport** [comment]
Hi, it seems there might have been an issue updating your Docker image.

Try running the following:
`sudo docker stop mconbot`
`sudo docker rm mconbot`
`sudo docker rmi raynieport/mconbot`
`sudo docker images` (check and make sure that raynieport/mconbot no longer exists)
`sudo docker run -dt --name mconbot --env-file .env raynieport/mconbot:amd64` (or :arm64 if you're running on an arm device)

Here's a screenshot of my Discord with a simple test bot:
![image](https://user-images.githubusercontent.com/83410313/147496350-e81bcac9-a6ee-4782-b1b7-5e1dcf80e6e6.png)

**Comment by RayNieport** [comment]
@Fynenix any luck updating the Docker image? If you're still having trouble I can try out your specific bot, although I'm fairly confident that the updated code should work for you.

**Comment by Fynenix** [comment]
Sorry for the late answer. Yes i could sucessfully update the Docker Image. Unfortunately i didn't work. Yes it would be great if you could test it with the bot i use.

**Comment by RayNieport** [comment]
Hello, I had a chance to test out the Integromat bot and am running into the same issue that you are. I'm not able to view their source code, so I can't figure out what is going wrong exactly.

mconBot is printing the following error:
`AttributeError: 'User' object has no attribute 'roles'`

I did some more digging and it seems that the Integromat bot is not joining the server as a typical "user", which means that the role-based system that mconBot uses is will not work with it. I edited the code as follows and it works:
![image](https://user-images.githubusercontent.com/83410313/148719288-d9e0ba5c-361f-4573-aaa6-e76693727c3b.png)

However, this disables the role-based system for only allowing certain users to execute high-level commands.
I will try to think of a way around this and let you know what I come up with.

**Comment by RayNieport** [comment]
@Fynenix  I finally solved the issue. Sorry to take so long figuring this out, I've been pretty busy around the holiday season.

Please update your Docker image again and check out the [new .env file](https://github.com/RayNieport/mconBot/blob/main/src/.env), which adds the line `BOT_LEVEL`. This will allow you to set the desired authorization level for any bots on your server (by default, bots have "user" privileges). 

Unfortunately I don't think I can make individual bots have different authorization levels, so you'll have to choose one level for all bots on the server. Currently the raynieport/mconbot:amd64 image is up to date, and I'm building the arm64 image for raspberry pi support (it should be done in a little while).

I really hope this works for you! I tested with Integromat it seems to work perfectly.
Thanks for your patience with this, let me know if you get it working!

**Comment by Fynenix** [comment]
Thank you so much. It worked. This is a great solution.

**Comment by RayNieport** [comment]
Glad it works for you! Thanks for submitting the issue. If you have any other feature requests, let me know.
